<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="../css/msgpage.css" rel="stylesheet" />
<link href="../css/include/footer_include.css" rel="stylesheet" />
<link href="../css/include/title_include.css" rel="stylesheet" />
<script type="text/javascript" src="../js/msgpage/index.js">
</script>
</head>
<body>
	<div id="CEN">
     <?php include_once APPLICATION_PATH.'/views/include/title_include.phtml'; ?>
        <div id="activity">
			<div id="a_left">
			   <div class='ll'></div>
			   <div class='ll'></div>
			    <div class='ll'></div>
			   <div class='ll'></div>
			</div>
			<div id="a_right">
				<form action="">
					<div><input></div>
					<div><input></div>
					<div><input></div>
				</form>
			</div>
			<div id="a_clear"></div>
		</div>
      <?php include_once APPLICATION_PATH.'/views/include/footer_include.phtml'; ?>
  </div>
</body>
</html>